[project]
name = "mcp-learning-start"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.14.0",
    "uvicorn>=0.35.0",
]
