[project]
name = "mcp-server-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.12.3",
    "uvicorn>=0.35.0",
]
